In [ ]:
import pandas as pd
from sklearn.cluster import KMeans

actor_genre_df = pd.read_csv("imdb_movies_2000to2022.actorXgenre.csv",
                             index_col="actor_id")

print("Matrix shape:", actor_genre_df.shape)
display(actor_genre_df.head())

Matrix shape: (33609, 25)

,Comedy,Fantasy,Romance,Drama,Mystery,Thriller,Action,Biography,Crime,War,...,Horror,Documentary,Sport,News,Family,Music,Unnamed: 22,Western,Short,Reality-TV
actor_id,,,,,,,,,,,,,,,,,,,,,
nm0000212,7.0,1.0,6.0,6.0,1.0,2.0,1.0,1.0,2.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
nm0413168,7.0,3.0,5.0,12.0,5.0,2.0,14.0,4.0,6.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
nm0000630,8.0,2.0,6.0,14.0,2.0,3.0,4.0,5.0,1.0,1.0,...,3.0,7.0,3.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
nm0005227,10.0,1.0,2.0,2.0,0.0,1.0,1.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0
nm0864851,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

#### Creating the eight clusters

In [8]:
model = KMeans(n_clusters=8) # initialize the model with 8 clusters
cluster_labels = model.fit_predict(actor_genre_df) # fit the model and get each actor's predicted cluster
print("Number of predictions:", len(cluster_predictions))

Number of predictions: 33609

#### Storing the cluster predictions

In [10]:
# DataFrame: 
# the index contains actor IDs
# the columns contain the predicted cluster
actor_clusters_df = pd.DataFrame({"cluster": cluster_predictions}, index=actor_genre_df.index)
display(actor_clusters_df.head())

           cluster
actor_id
nm0000212        1
nm0413168        2
nm0000630        2
nm0005227        1
nm0864851        0

#### The number of actors in each cluster

In [12]:
cluster_sizes = (actor_clusters_df["cluster"].value_counts().sort_index())
print("Number of actors per cluster:")
print(cluster_sizes)

Number of actors per cluster:
cluster
0    14682
1      321
2      316
3     1862
4      893
5    15445
6       89
7        1
Name: count, dtype: int64

#### Five random selected actors from each cluster

In [19]:
print("Random sample of 5 actors from each clusters:")

for cluster_id, cluster_group in actor_clusters_df.groupby("cluster"):
    sample_size = min(5, len(cluster_group))
    random_actors = cluster_group.sample(n=sample_size, random_state=42)

    print(f"\nCluster {cluster_id}")
    print(f"Total actors: {len(cluster_group)}")

    for actor_id in random_actors.index:
        print(f"Actor ID: {actor_id}")

Random sample of 5 actors from each clusters:

Cluster 0
Total actors: 14682
Actor ID: nm0768936
Actor ID: nm0842374
Actor ID: nm0690803
Actor ID: nm0502273
Actor ID: nm4464150

Cluster 1
Total actors: 321
Actor ID: nm0579756
Actor ID: nm0004965
Actor ID: nm0366389
Actor ID: nm0002006
Actor ID: nm0000207

Cluster 2
Total actors: 316
Actor ID: nm0001667
Actor ID: nm0593664
Actor ID: nm0165101
Actor ID: nm0000368
Actor ID: nm0722636

Cluster 3
Total actors: 1862
Actor ID: nm0065942
Actor ID: nm0201903
Actor ID: nm0555500
Actor ID: nm0517638
Actor ID: nm0889522

Cluster 4
Total actors: 893
Actor ID: nm0592799
Actor ID: nm0197647
Actor ID: nm0781913
Actor ID: nm2496992
Actor ID: nm0001277

Cluster 5
Total actors: 15445
Actor ID: nm0000470
Actor ID: nm6598222
Actor ID: nm4135862
Actor ID: nm4588704
Actor ID: nm0680919

Cluster 6
Total actors: 89
Actor ID: nm0000241
Actor ID: nm0005068
Actor ID: nm0005048
Actor ID: nm0000230
Actor ID: nm0005458

Cluster 7
Total actors: 1
Actor ID: nm0000616